<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Addition</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c1a3aaf6-d20e-44b1-aaac-1256873fea65</testSuiteGuid>
   <testCaseLink>
      <guid>c4a9c96d-eacc-43da-a221-9d1daaf0122a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>0</defaultValue>
         <description></description>
         <id>99ee7b2a-b726-443d-a6d3-d559b71bebff</id>
         <masked>false</masked>
         <name>IntA2</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/API/SOAP/TC-SOAP-ADD</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d8c3e682-d84f-4377-bf21-8d259c5cd153</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestValues</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d8c3e682-d84f-4377-bf21-8d259c5cd153</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IntA1</value>
         <variableId>eefa0dbe-4986-44b3-ad8a-7722de3d8b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d8c3e682-d84f-4377-bf21-8d259c5cd153</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IntA2</value>
         <variableId>99ee7b2a-b726-443d-a6d3-d559b71bebff</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
